from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(751, 431)
        self.Tw_Registros = QtWidgets.QTableWidget(Dialog)
        self.Tw_Registros.setGeometry(QtCore.QRect(380, 100, 331, 251))
        self.Tw_Registros.setObjectName("Tw_Registros")
        self.Tw_Registros.setColumnCount(0)
        self.Tw_Registros.setRowCount(0)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 62, 20))
        self.label.setObjectName("label")
        self.Le_Nombre = QtWidgets.QLineEdit(Dialog)
        self.Le_Nombre.setGeometry(QtCore.QRect(90, 50, 161, 32))
        self.Le_Nombre.setObjectName("Le_Nombre")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 62, 20))
        self.label_2.setObjectName("label_2")
        self.Le_Apellidos = QtWidgets.QLineEdit(Dialog)
        self.Le_Apellidos.setGeometry(QtCore.QRect(90, 100, 161, 32))
        self.Le_Apellidos.setObjectName("Le_Apellidos")
        self.Le_Email = QtWidgets.QLineEdit(Dialog)
        self.Le_Email.setGeometry(QtCore.QRect(90, 150, 161, 32))
        self.Le_Email.setObjectName("Le_Email")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 62, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 210, 62, 20))
        self.label_4.setObjectName("label_4")
        self.Le_Rol = QtWidgets.QLineEdit(Dialog)
        self.Le_Rol.setGeometry(QtCore.QRect(90, 200, 161, 32))
        self.Le_Rol.setObjectName("Le_Rol")
        self.Le_Buscar = QtWidgets.QLineEdit(Dialog)
        self.Le_Buscar.setGeometry(QtCore.QRect(380, 60, 231, 32))
        self.Le_Buscar.setObjectName("Le_Buscar")
        self.Btn_Buscar = QtWidgets.QPushButton(Dialog)
        self.Btn_Buscar.setGeometry(QtCore.QRect(620, 60, 92, 32))
        self.Btn_Buscar.setObjectName("Btn_Buscar")
        self.Btn_Editar = QtWidgets.QPushButton(Dialog)
        self.Btn_Editar.setGeometry(QtCore.QRect(380, 370, 92, 32))
        self.Btn_Editar.setObjectName("Btn_Editar")
        self.Btn_Eliminar = QtWidgets.QPushButton(Dialog)
        self.Btn_Eliminar.setGeometry(QtCore.QRect(620, 370, 92, 32))
        self.Btn_Eliminar.setObjectName("Btn_Eliminar")
        self.Btn_Guardar = QtWidgets.QPushButton(Dialog)
        self.Btn_Guardar.setGeometry(QtCore.QRect(20, 320, 92, 32))
        self.Btn_Guardar.setObjectName("Btn_Guardar")
        self.Btn_Actualizar = QtWidgets.QPushButton(Dialog)
        self.Btn_Actualizar.setGeometry(QtCore.QRect(170, 320, 92, 32))
        self.Btn_Actualizar.setObjectName("Btn_Actualizar")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 260, 62, 20))
        self.label_5.setObjectName("label_5")
        self.Le_Sueldo = QtWidgets.QLineEdit(Dialog)
        self.Le_Sueldo.setGeometry(QtCore.QRect(90, 250, 161, 32))
        self.Le_Sueldo.setObjectName("Le_Sueldo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Nombre"))
        self.label_2.setText(_translate("Dialog", "Apellidos"))
        self.label_3.setText(_translate("Dialog", "E-mail"))
        self.label_4.setText(_translate("Dialog", "Rol"))
        self.Btn_Buscar.setText(_translate("Dialog", "Buscar"))
        self.Btn_Editar.setText(_translate("Dialog", "Editar"))
        self.Btn_Eliminar.setText(_translate("Dialog", "Eliminar"))
        self.Btn_Guardar.setText(_translate("Dialog", "Guardar"))
        self.Btn_Actualizar.setText(_translate("Dialog", "Actualizar"))
        self.label_5.setText(_translate("Dialog", "Sueldo"))
